version: "3.9"

services:
  db:
    image: postgres:17
    container_name: db_postgres
    volumes:
      - ~/.pg/db_data/Users_Directory:/var/lib/postgresql/data
    env_file:
      - .env


  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  
      && gunicorn -b 0.0.0.0:8000 Users_Directory.wsgi:application"
  
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: app_nginx
    image: app_nginx
    volumes:
        - static_volume:/app/static
       # - static_volume:/app/static
       # - certs:/etc/nginx/certs
       # - vhost:/etc/nginx/vhost.d
       # - html:/usr/share/nginx/html
       # - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
        - web
    ports:
        - "${NGINX_EXTERNAL_PORT}:80"
        - "${NGINX_EXTERNAL_SSL_PORT}:443"



  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

volumes:
  static_volume:
  db_data:
