version: "3.8"

services:
    web:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DATABASE_URL: postgres://user:password@db/Users

    db:
      image: postgres:13
      environment:
        POSTGRES_DB: Users
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
        - db_data:/var/lib/postgresql/data

    prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"

    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"

volumes:
  db_data: